package com.formsaathi.pdf

import android.graphics.pdf.PdfRenderer
import android.net.Uri
import android.os.ParcelFileDescriptor
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.formsaathi.contracts.FakeFormParser
import com.formsaathi.model.AnswerSource
import com.formsaathi.model.FormAnswer
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/**
 * Production PDF generation proof for AndroidCompletedPdfGenerator.
 *
 * Verifies:
 * 1. A valid two-page source PDF is generated by SamplePdfFactory.
 * 2. Answers for both page 1 and page 2 are supplied using real fake-parser field IDs.
 * 3. The test clearly fails if page-two annual-income (field_annual_income) is missing.
 * 4. A non-empty completed PDF is generated by AndroidCompletedPdfGenerator.
 * 5. The completed PDF can be reopened and rendered by Android's PdfRenderer.
 * 6. The completed PDF has exactly two pages in the original order.
 */
@RunWith(AndroidJUnit4::class)
class AndroidCompletedPdfGeneratorTest {

    @Test
    fun testGenerateCompletedPdfProducesValidReopenableMultiPagePdf() = runBlocking {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val cacheDir = context.cacheDir

        // 1. Generate and verify valid 2-page source PDF
        val sourceFile = SamplePdfFactory.createSamplePdf(cacheDir)
        val sourceUri = Uri.fromFile(sourceFile)
        assertTrue("Source PDF file must exist", sourceFile.exists())
        assertTrue("Source PDF file must be non-empty", sourceFile.length() > 0)

        // Verify source PDF can be opened and has exactly 2 pages
        ParcelFileDescriptor.open(sourceFile, ParcelFileDescriptor.MODE_READ_ONLY).use { srcPfd ->
            val srcRenderer = PdfRenderer(srcPfd)
            try {
                assertEquals("Source PDF must have exactly 2 pages", 2, srcRenderer.pageCount)
                srcRenderer.openPage(0).use { p0 ->
                    assertEquals(0, p0.index)
                    assertTrue("Page 0 width must be positive", p0.width > 0)
                    assertTrue("Page 0 height must be positive", p0.height > 0)
                }
                srcRenderer.openPage(1).use { p1 ->
                    assertEquals(1, p1.index)
                    assertTrue("Page 1 width must be positive", p1.width > 0)
                    assertTrue("Page 1 height must be positive", p1.height > 0)
                }
            } finally {
                srcRenderer.close()
            }
        }

        // 2. Parse form with FakeFormParser
        val parser = FakeFormParser()
        val parsedForm = parser.parse(sourceUri)
        assertEquals("Parsed form must have 2 pages", 2, parsedForm.pages.size)

        // 3. Prepare answers for both page 1 and page 2 using real FakeFormParser IDs
        // Note: Page 2 annual income is 'field_annual_income' (not 'field_income')
        val answers = mapOf(
            // Page 1 fields (pageIndex = 0)
            "field_full_name" to FormAnswer("field_full_name", "Aarav Sharma", "AARAV SHARMA", AnswerSource.TYPED),
            "field_father_name" to FormAnswer("field_father_name", "Rajesh Sharma", "RAJESH SHARMA", AnswerSource.TYPED),
            "field_dob" to FormAnswer("field_dob", "15/08/1995", "15/08/1995", AnswerSource.TYPED),
            "field_gender" to FormAnswer("field_gender", "Male", "Male", AnswerSource.TYPED),
            "field_mobile" to FormAnswer("field_mobile", "9876543210", "9876543210", AnswerSource.TYPED),
            "field_email" to FormAnswer("field_email", "aarav@example.com", "aarav@example.com", AnswerSource.TYPED),
            "field_aadhaar" to FormAnswer("field_aadhaar", "123456789012", "1234 5678 9012", AnswerSource.TYPED),
            "field_permanent_address" to FormAnswer("field_permanent_address", "Flat 101, Galaxy Apts, Pune", "Flat 101, Galaxy Apts, Pune", AnswerSource.TYPED),
            "field_same_as_permanent" to FormAnswer("field_same_as_permanent", "yes", "yes", AnswerSource.TYPED),
            "field_current_address" to FormAnswer("field_current_address", "Flat 101, Galaxy Apts, Pune", "Flat 101, Galaxy Apts, Pune", AnswerSource.COPIED_BY_RULE),
            // Page 2 fields (pageIndex = 1)
            "field_category" to FormAnswer("field_category", "General", "General", AnswerSource.TYPED),
            "field_annual_income" to FormAnswer("field_annual_income", "500000", "500000", AnswerSource.TYPED)
        )

        // Verify that all answer keys correspond to real fake-parser field IDs
        val validFieldIds = parsedForm.fields.map { it.id }.toSet()
        for (answerKey in answers.keys) {
            assertTrue("Answer key '$answerKey' must match a real field ID in FakeFormParser", validFieldIds.contains(answerKey))
        }

        // Verify answers are provided for both page 1 (index 0) and page 2 (index 1)
        val page0Answered = answers.keys.any { key -> parsedForm.fields.any { it.id == key && it.pageIndex == 0 } }
        val page1Answered = answers.keys.any { key -> parsedForm.fields.any { it.id == key && it.pageIndex == 1 } }
        assertTrue("Answers must include page 1 fields", page0Answered)
        assertTrue("Answers must include page 2 fields", page1Answered)

        // Enforce that page-two annual income is present with real ID 'field_annual_income'
        verifyPageTwoAnnualIncomePresent(answers)

        // 4. Output destination
        val outputFile = File(cacheDir, "test_output_completed.pdf")
        if (outputFile.exists()) outputFile.delete()
        val outputUri = Uri.fromFile(outputFile)

        // 5. Generate completed PDF using production AndroidCompletedPdfGenerator
        val generator = AndroidCompletedPdfGenerator(context)
        val result = generator.generate(sourceUri, parsedForm, answers, outputUri)

        // 6. Verify generation completed and output is non-empty
        assertNotNull("GenerationResult must not be null", result)
        assertTrue("Output file must exist", outputFile.exists())
        assertTrue("Output file must be non-empty", outputFile.length() > 0)

        // 7. Verify output can be reopened by PdfRenderer with exactly 2 pages in original order
        ParcelFileDescriptor.open(outputFile, ParcelFileDescriptor.MODE_READ_ONLY).use { pfd ->
            val renderer = PdfRenderer(pfd)
            try {
                assertEquals("Generated completed PDF must have exactly 2 pages", 2, renderer.pageCount)

                // Page 0 (First page in order)
                renderer.openPage(0).use { page0 ->
                    assertEquals("First page index must be 0", 0, page0.index)
                    assertTrue("Page 0 width must be positive", page0.width > 0)
                    assertTrue("Page 0 height must be positive", page0.height > 0)
                }

                // Page 1 (Second page in order)
                renderer.openPage(1).use { page1 ->
                    assertEquals("Second page index must be 1", 1, page1.index)
                    assertTrue("Page 1 width must be positive", page1.width > 0)
                    assertTrue("Page 1 height must be positive", page1.height > 0)
                }
            } finally {
                renderer.close()
            }
        }
    }

    @Test(expected = AssertionError::class)
    fun testFailsIfPageTwoAnnualIncomeIsMissingFromAnswers() {
        // Answers missing the required page-two annual income field
        val incompleteAnswers = mapOf(
            "field_full_name" to FormAnswer("field_full_name", "Aarav", "Aarav", AnswerSource.TYPED),
            "field_category" to FormAnswer("field_category", "General", "General", AnswerSource.TYPED),
            // Intentionally using incorrect legacy field ID 'field_income' instead of 'field_annual_income'
            "field_income" to FormAnswer("field_income", "500000", "500000", AnswerSource.TYPED)
        )

        // This must fail because 'field_annual_income' is missing from supplied answers
        verifyPageTwoAnnualIncomePresent(incompleteAnswers)
    }

    /**
     * Verifies that the required page-two annual income field ('field_annual_income')
     * is supplied in the answers map. Fails clearly if missing or if the legacy 'field_income' ID was used.
     */
    private fun verifyPageTwoAnnualIncomePresent(answers: Map<String, FormAnswer>) {
        assertTrue(
            "Answers must contain page-two 'field_annual_income' (found keys: ${answers.keys})",
            answers.containsKey("field_annual_income") && !answers["field_annual_income"]?.normalizedValue.isNullOrBlank()
        )
    }
}
